#!/usr/bin/env python3
"""Generate or verify a Redis DUMP produced by an official FalkorDB server.

The generate mode runs against upstream FalkorDB and writes the exact Redis DUMP
bytes for a graph containing representative persisted values, indexes,
constraints, and multi-edges.

The verify mode restores those unmodified bytes into the native Windows host
and proves the graph is queryable with its schema intact.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from falkordb import FalkorDB
from redis import Redis
from redis.exceptions import ResponseError

GRAPH = "upstream-real-fixture"
RESTORED = "upstream-real-fixture-restored"


def endpoint_kwargs(args, *, include_protocol: bool) -> dict:
    kwargs = {
        "host": args.host,
        "port": args.port,
        "password": args.password,
        "socket_connect_timeout": 10,
        "socket_timeout": 30,
        "ssl": args.ssl,
    }
    if include_protocol:
        kwargs["protocol"] = 2
        kwargs["decode_responses"] = False
    if args.ssl:
        if args.ca:
            kwargs["ssl_ca_certs"] = args.ca
            kwargs["ssl_cert_reqs"] = "required"
        if args.cert:
            kwargs["ssl_certfile"] = args.cert
        if args.key:
            kwargs["ssl_keyfile"] = args.key
    return kwargs


def redis_client(args) -> Redis:
    return Redis(**endpoint_kwargs(args, include_protocol=True))


def falkor_client(args) -> FalkorDB:
    return FalkorDB(**endpoint_kwargs(args, include_protocol=False))


def generate(args) -> None:
    raw = redis_client(args)
    db = falkor_client(args)
    try:
        try:
            raw.execute_command("GRAPH.DELETE", GRAPH)
        except ResponseError:
            pass

        graph = db.select_graph(GRAPH)
        graph.create_node_range_index("Person", "age")
        graph.create_node_range_index("Person", "name", "age")
        graph.create_node_fulltext_index("Person", "name")
        graph.query(
            "CREATE (a:Person {name:'Alice',age:40}),"
            "(b:Person {name:'Bob',age:30}),"
            "(a)-[:KNOWS {since:2026}]->(b),"
            "(a)-[:PARALLEL {slot:1}]->(b),"
            "(a)-[:PARALLEL {slot:2}]->(b)"
        )
        graph.create_node_unique_constraint("Person", "name")
        constraints = graph.list_constraints()
        assert any(
            c["type"] == "UNIQUE"
            and c["label"] == "Person"
            and "name" in c["properties"]
            for c in constraints
        ), constraints

        graph.query(
            "CREATE (:Types {"
            "strval:'str', numval:5.5, boolval:true, array:[1,2,3], "
            "pointval:point({latitude:5.5, longitude:6}), "
            "vector:vecf32([1,0,3]), "
            "date:date({year:1984,month:10,day:21}), "
            "time:localtime({hour:10,minute:30,second:10}), "
            "datetime:localdatetime({year:1984,month:10,day:21,hour:5,minute:30,second:10}), "
            "duration:duration({years:1,months:1,days:1,hours:1,minutes:1,seconds:1}), "
            "unicode:'Δ🚀漢字'"
            "})"
        )

        # Force FalkorDB's >256 KiB standalone blob serializer path. The
        # repeating pattern also makes Redis apply LZF to the surrounding DUMP
        # chunks, so this one fixture exercises both layers.
        large_payload = "0123456789abcdef" * 20_000
        graph.query(
            "CREATE (:Large {payload:$payload})",
            params={"payload": large_payload},
        )

        # Leave deleted entity IDs/tombstones in the graph before persistence.
        graph.query(
            "CREATE (a:Transient {id:1})-[r:TMP]->(b:Transient {id:2})"
        )
        graph.query("MATCH (n:Transient) DETACH DELETE n")

        assert graph.query(
            "MATCH (n:Person) WHERE n.age >= 35 RETURN n.name"
        ).result_set == [["Alice"]]
        assert graph.query(
            "CALL db.idx.fulltext.queryNodes('Person','Alice') "
            "YIELD node RETURN node.name"
        ).result_set == [["Alice"]]

        payload = raw.dump(GRAPH)
        if not payload:
            raise RuntimeError("upstream FalkorDB returned an empty DUMP payload")

        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(payload)

        info = raw.info(section="server")
        manifest = {
            "graph": GRAPH,
            "dump_bytes": len(payload),
            "redis_version": str(info.get("redis_version") or info.get(b"redis_version") or ""),
            "redis_mode": str(info.get("redis_mode") or info.get(b"redis_mode") or ""),
        }
        args.output.with_suffix(args.output.suffix + ".json").write_text(
            json.dumps(manifest, sort_keys=True, indent=2),
            encoding="utf-8",
        )
        print(f"UPSTREAM_FALKORDB_DUMP_GENERATED bytes={len(payload)}")
    finally:
        db.close()
        raw.close()


def verify(args) -> None:
    payload = args.input.read_bytes()
    raw = redis_client(args)
    db = falkor_client(args)
    try:
        if not args.skip_restore:
            try:
                raw.execute_command("GRAPH.DELETE", RESTORED)
            except ResponseError:
                pass

            reply = raw.restore(RESTORED, 0, payload)
            if reply not in (True, b"OK", "OK"):
                raise RuntimeError(f"unexpected RESTORE reply: {reply!r}")

        graph = db.select_graph(RESTORED)

        people = graph.query(
            "MATCH (n:Person) RETURN n.name,n.age ORDER BY n.name"
        ).result_set
        assert people == [["Alice", 40], ["Bob", 30]], people

        knows = graph.query(
            "MATCH (:Person {name:'Alice'})-[r:KNOWS]->(:Person {name:'Bob'}) "
            "RETURN r.since"
        ).result_set
        assert knows == [[2026]], knows

        parallel = graph.query(
            "MATCH (:Person {name:'Alice'})-[r:PARALLEL]->(:Person {name:'Bob'}) "
            "RETURN r.slot ORDER BY r.slot"
        ).result_set
        assert parallel == [[1], [2]], parallel

        types = graph.query(
            "MATCH (p:Types) RETURN "
            "p.boolval,p.numval,p.strval,p.array,p.pointval,p.vector,"
            "p.date,p.time,p.datetime,p.duration,p.unicode"
        ).result_set
        assert len(types) == 1, types
        assert types[0][-1] == "Δ🚀漢字", types

        large = graph.query(
            "MATCH (n:Large) RETURN size(n.payload), "
            "substring(n.payload,0,16), substring(n.payload,size(n.payload)-16)"
        ).result_set
        assert large == [[320000, "0123456789abcdef", "0123456789abcdef"]], large

        transient = graph.query(
            "MATCH (n:Transient) RETURN count(n)"
        ).result_set
        assert transient == [[0]], transient

        indexes = graph.query(
            "CALL db.indexes() YIELD label,properties,types "
            "WHERE label='Person' RETURN properties,types"
        ).result_set
        assert any(
            row[0] == ["name", "age"] or row[0] == ["age", "name"]
            for row in indexes
        ), indexes

        ranged = graph.query(
            "MATCH (n:Person) WHERE n.age >= 35 RETURN n.name"
        ).result_set
        assert ranged == [["Alice"]], ranged

        fulltext = graph.query(
            "CALL db.idx.fulltext.queryNodes('Person','Alice') "
            "YIELD node RETURN node.name"
        ).result_set
        assert fulltext == [["Alice"]], fulltext

        constraints = graph.list_constraints()
        assert any(
            c["type"] == "UNIQUE"
            and c["label"] == "Person"
            and "name" in c["properties"]
            for c in constraints
        ), constraints

        try:
            graph.query("CREATE (:Person {name:'Alice',age:99})")
            raise AssertionError("restored upstream UNIQUE constraint accepted duplicate")
        except ResponseError:
            pass

        # Prove that deleted-ID bookkeeping did not corrupt allocation after
        # import. Only mutate during the first verification; restart mode then
        # proves this native post-import write is durable too.
        if not args.skip_restore:
            graph.query("CREATE (:AfterDelete {v:1})")
        after_delete = graph.query(
            "MATCH (n:AfterDelete) RETURN count(n)"
        ).result_set
        assert after_delete == [[1]], after_delete

        if args.roundtrip_output is not None:
            roundtrip = raw.dump(RESTORED)
            if not roundtrip:
                raise RuntimeError("endpoint returned an empty round-trip DUMP payload")
            args.roundtrip_output.parent.mkdir(parents=True, exist_ok=True)
            args.roundtrip_output.write_bytes(roundtrip)
            print(
                f"FALKORDB_ROUNDTRIP_DUMP_WRITTEN bytes={len(roundtrip)} "
                f"path={args.roundtrip_output}"
            )

        if args.skip_restore:
            print("UPSTREAM_FALKORDB_DUMP_RESTART_PASS")
        else:
            print("UPSTREAM_FALKORDB_DUMP_RESTORE_PASS")
    finally:
        db.close()
        raw.close()


def add_endpoint_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=6379)
    parser.add_argument("--password")
    parser.add_argument("--ssl", action="store_true")
    parser.add_argument("--ca")
    parser.add_argument("--cert")
    parser.add_argument("--key")


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="mode", required=True)

    gen = sub.add_parser("generate")
    add_endpoint_args(gen)
    gen.add_argument("--output", type=Path, required=True)

    ver = sub.add_parser("verify")
    add_endpoint_args(ver)
    ver.add_argument("--input", type=Path, required=True)
    ver.add_argument(
        "--skip-restore",
        action="store_true",
        help="query an already-restored fixture, used after a hard server restart",
    )
    ver.add_argument(
        "--roundtrip-output",
        type=Path,
        help="after verification, DUMP the restored graph to this path",
    )

    args = parser.parse_args()
    if args.mode == "generate":
        generate(args)
    else:
        verify(args)


if __name__ == "__main__":
    main()
